title: Lakshmi Yetukuri
logo: /assets/img/1597817686827.jpg
description: I am GCP data architect who want to upgrade myself as a Data Scientist/Gen AI Architect.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
